# Custom 00-minime.conf overlay for H700 Handhelds
# (Only defines parameters supported by our optimized monolithic kernel)

# Prevents SYN DOS attacks.
net.ipv4.tcp_syncookies = 1

# Prevents ip spoofing.
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1

# Only groups within this id range can use ping.
net.ipv4.ping_group_range = 999 59999

# Redirects can potentially be used to maliciously alter hosts routing tables.
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 1

# The source routing feature includes some known vulnerabilities.
net.ipv4.conf.all.accept_source_route = 0

# See RFC 1337
net.ipv4.tcp_rfc1337 = 1

# Restarts computer after 120 seconds after kernel panic
kernel.panic = 120
