boot|devfs
boot|dmesg
boot|mdev
boot|hwdrivers
boot|modules
boot|sysctl
boot|hostname
boot|bootmisc
boot|syslog
boot|localmount
boot|dbus
boot|unblank
default|bluetooth
default|iwd
default|wifi
default|telnetd
default|ftpd
