name: Build Bootloader

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build-bootloader:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Set safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Restore Bootloader Cache
        id: cache-bootloader-restore
        uses: actions/cache/restore@v6
        with:
          path: packages/bootloader
          key: bootloader-${{ hashFiles('packages/bootloader/**/config/**', 'packages/bootloader/**/patches/**', 'packages/bootloader/build.sh') }}

      - name: Restore Bootloader CCache
        id: ccache-bootloader-restore
        uses: actions/cache/restore@v6
        with:
          path: ~/.bootloader-ccache
          key: ccache-bootloader-${{ github.sha }}
          restore-keys: |
            ccache-bootloader-

      - name: Compile Bootloader
        id: compile-bootloader
        if: steps.cache-bootloader-restore.outputs.cache-hit != 'true' || hashFiles('packages/bootloader/h700/out/u-boot-sunxi-with-spl.bin', 'packages/bootloader/rk3326/out/idbloader.img', 'packages/bootloader/rk3566/out/idbloader.img') == ''
        run: |
          docker run --rm -u root \
            -v "$HOME/.bootloader-ccache:/root/.ccache" \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -w /workspace \
            "ghcr.io/${{ github.repository_owner }}/minime-glibc:latest" \
            /bin/bash -c "packages/bootloader/build.sh rk3326 2026.07 && packages/bootloader/build.sh rk3566 2026.07 && packages/bootloader/build.sh h700 2026.07 && chown -R \$(stat -c '%u:%g' /workspace) /workspace/packages/bootloader"
          sudo chown -R "$USER:$USER" packages/bootloader

      - name: Save Bootloader Cache
        if: always() && steps.compile-bootloader.outcome == 'success'
        uses: actions/cache/save@v6
        with:
          path: packages/bootloader
          key: bootloader-${{ hashFiles('packages/bootloader/**/config/**', 'packages/bootloader/**/patches/**', 'packages/bootloader/build.sh') }}

      - name: Save Bootloader CCache
        if: always() && steps.compile-bootloader.outcome == 'success'
        uses: actions/cache/save@v6
        with:
          path: ~/.bootloader-ccache
          key: ccache-bootloader-${{ github.sha }}

      - name: Upload Bootloader Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: bootloader-out
          path: |
            packages/bootloader/h700/out
            packages/bootloader/rk3326/out
            packages/bootloader/rk3566/out
          retention-days: 7
